phenology/springtime

- README.md
> test from branch

- src/springtime/datasets/PEP725Phenor.py
> Small edits for pep725

- README.md
- pyproject.toml
- src/springtime/datasets/PEP725Phenor.py
- src/springtime/datasets/__init__.py
- src/springtime/datasets/daymet.py
- src/springtime/datasets/ppo.py
- src/springtime/main.py
- tests/recipes/ppo.yaml
> PPO support

- src/springtime/datasets/ppo.py
> Remove all references to source

- pyproject.toml
- src/springtime/datasets/__init__.py
- src/springtime/datasets/e_obs.py
- tests/recipes/eobs.yaml
> Add E-OBS dataset

- .github/workflows/lint.yml
- docs/develop.md
- environment.yml
Refs #79
Tested with
```shell
docker run -ti --rm -v $PWD/environment.yml:/environment.yml condaforge/mambaforge bash
```
followed by the [install instructions](https://github.com/phenology/springtime/blob/main/docs/develop.md#requirements)
Only compiles BayesianTools and regenoud.
> Less compiles for R

- src/springtime/datasets/NPNPhenor.py
> Return pandas dataframe for npn_species

- .github/workflows/lint.yml
- README.md
- docs/develop.md
- src/springtime/datasets/__init__.py
- src/springtime/datasets/phenocam.py
- tests/recipes/phenocam.yaml
> Phenocam dataset

- src/springtime/datasets/daymet.py
- src/springtime/datasets/e_obs.py
- src/springtime/datasets/phenocam.py
- src/springtime/datasets/rnpn.py
- src/springtime/utils.py
- tests/recipes/daymet.yaml
- tests/recipes/eobs.yaml
- tests/recipes/phenocam.yaml
> Use NamedArea in each dataset

- docs/usage.md
> Add missing usage file

- docs/notebooks/datasets_daymet.ipynb
- src/springtime/datasets/daymet.py
- tests/recipes/daymet.yaml
> Add variables selection to DaymetSinglePoint and DaymetMultiplePoints

- src/springtime/datasets/abstract.py
- src/springtime/datasets/daymet.py
- src/springtime/datasets/modis.py
- src/springtime/datasets/rnpn.py
- src/springtime/main.py
- src/springtime/recipes/model_comparison_usecase.yaml
- src/springtime/utils.py
> Do resample

- environment.yml
- src/springtime/datasets/daymet.py
- src/springtime/main.py
> Do transpose

- .readthedocs.yaml
- pyproject.toml
- src/springtime/datasets/modis.py
- src/springtime/experiment.py
- src/springtime/main.py
- src/springtime/models/__init__.py
- src/springtime/recipes/model_comparison_usecase.yaml
- tests/test_experiment.py
> Add pydantic models wrapping pycaret

- src/springtime/datasets/e_obs.py
> Make eobs load() methods return datetime,geometry + vars dataframe

- src/springtime/datasets/daymet.py
> Fix DaymetBoundingBox 

- src/springtime/datasets/PEP725Phenor.py
> Fix PEP725Phenor

- .github/workflows/lint.yml
- pyproject.toml
- src/springtime/NestedFitRegressionExperiment.py
- src/springtime/datasets/phenocam.py
- src/springtime/datasets/ppo.py
- src/springtime/experiment.py
- src/springtime/main.py
- src/springtime/recipes/model_comparison_usecase.yaml
Fixes #152 
* our MERF fork was added as a git dependency, to put springtime on pypi we need to install our MERF from pypi 
* The fit_kwargs arg for compare_models is used for every model.
* Solution: Made fit_kwargs nested by model.
* MERF needs cluster column 
* Solution: Add derived feature latitude and use a cluster column
* Other possibilities:
* Use categorical column, but most models do not understand feature of string type
* Use lookup table for geomertry, using pandas factorized(), but different dataset would have same number for different location.
> Run merf from recipe

- src/springtime/datasets/phenocam.py
- src/springtime/datasets/ppo.py
- tests/recipes/phenocam.yaml
- tests/recipes/ppo.yaml
closes #150
see the issue for details.
> Add input argument variables to phenocam and ppo datasets

- docs/user_guide/datasets/modis.ipynb
- src/springtime/datasets/pep725.py
Make the docs consistent with the paths springtime is looking for
> Fix credential paths in docs

- .github/workflows/build-image.yml
Build and push a new image for every new package release
> Build and upload Docker image using GitHub action
